redis: update examples and fix secure redis configuration
nais/doc pull request #107
Opened 2020-09-18 08:05 UTC by tronghn

The default `redis` baseimage doesn't support setting password without supplying a `.conf` file with some expected key/value format. If you've created a secret containing `REDIS_PASSWORD` for configuring the redis metrics exporter image, then you'll have to duplicate the password value to another secret for configuring the `redis` instance itself.

We'd have to either use vanilla k8s to set the password through the command line arguments, or use a custom image that supports supplying the password. The latter involves the least amount of work, so the examples are updated to recommend using this.

Live preview here: https://doc.nais.io/v/redis-cleanup/persistence/redis

2020-09-21 05:33 UTC, Kyrremann requested changes
Bra jobba! Gammel tekst som må endres.

2020-09-21 05:33 UTC, Kyrremann commented on persistence/redis.md
> +`nais.yaml` for the simplest version of such an exporter is found below. NAIS has also made a dashboard that everyone
`...such an exporter is found below.` Gammel tekst som refererer til eksempel under. Må endres til å peke oppover.

2020-09-21 05:33 UTC, Kyrremann commented on persistence/redis.md
> +{% hint style="info" %}
Tror det hadde sett best ut om hint om komplett eksempel kom etter infoen om hvordan du mounter en hemmelighet.

2020-09-21 10:18 UTC, tronghn commented
On hold. Investigating if this works in gcp as well

2020-09-22 11:47 UTC, tronghn commented
Merger inn denne as-is da det retter på docen som er live nå som ikke fungerer helt, så kan vi ta oppsett for GCP i en egen PR.

2020-09-22 11:47 UTC, merged