Gcp projects
nais/doc pull request #148
Opened 2020-11-27 15:22 UTC by Kyrremann

2020-11-27 16:01 UTC, x10an14 requested changes
Awesome!

Just minor typos and some readability and some norwegian phrasing/grammar in the text.
See comments =).

2020-11-27 16:01 UTC, x10an14 commented on docs/basics/teams.md
> +Some time you end up giving a wider access than needed, but GCP has a IAM recommender that will monitor each access given, and compare it to the access used.
```suggestion
Sometimes you might end up giving more (a wider) access than strictly - but fear not!
GCP has an IAM recommender which will monitor each access permission given, and compare it to accesses actually asked for/required aftwards.
```

2020-11-27 16:01 UTC, x10an14 commented on docs/basics/teams.md
> +Then the IAM recommender will recommend a more granular access, that is probably more fitting for the user.
```suggestion
After which the IAM recommender will recommend a more granular access, that probably fits you and your usage better!
```

2020-11-30 07:26 UTC, Kyrremann commented on docs/basics/teams.md
> +Remember to clean up after yourself, so we don't have unnecessary resources running, and costing us money.
Kunne vi funnet et annet ord enn `leveraged` her? Måtte slå det opp, men hjalp meg ikke i å forstå setningen din.

2020-11-30 07:28 UTC, Kyrremann commented on docs/basics/teams.md
> +Google Docs has a list of possible [predefined roles](https://cloud.google.com/iam/docs/understanding-roles#predefined_roles) that we recommend using.
Kanskje forenkle `keeping in mind/teams leverage` til å ikke ha `/`, blir litt enklere å lese da. For eksempel bare `using`. Da jeg vil tro det beste er at folk gjenbruker de rollene, i stedet for å prøve å lage sine egne.

2020-11-30 07:29 UTC, Kyrremann commented on docs/basics/teams.md
> +These roles can also be listed our with `gcloud iam roles list --filter $feature`.
Kan prøve å lage en mer beskrivende tekst. Filteret var ikke så veldig bra. Kan hende den enkle løsningen er å bytte det `feature` med `roleName`.

Feature er vel uansett ikke forklart i denne konteksten, som er litt dumt. Kan hende, på et generelt basis, bør bytte det ut med `product`.

2020-11-30 07:31 UTC, Kyrremann commented on docs/basics/teams.md
> +gcloud projects add-iam-policy-binding <PROJECT_ID> --member=user:<FIRSTNAME>.<LASTNAME>@nav.no --role=<ROLE_NAME> --condition="expression=request.time < timestamp('$(date -v '+1H' -u +'%Y-%m-%dT%H:%
Tenker vi flytte bash-kommentaren din ut i teksten ovenfor, så det ikke blir så mye gjentakelse.

2020-11-30 07:35 UTC, Kyrremann commented on docs/basics/teams.md
> +A service account is also a `--member` of a project, but instead of running the command using in the previous paragraph, you change `--member=user:<email>` to `--member=serviceAccount:<email>`.
Hva ønsker du å teste lokalt?

2020-11-30 07:35 UTC, Kyrremann commented on docs/basics/teams.md
> +#### Temporary access
God idé!

2020-11-30 07:36 UTC, Kyrremann commented on docs/basics/teams.md
> +Some time you end up giving a wider access than needed, but GCP has a IAM recommender that will monitor each access given, and compare it to the access used.
Foreslår å droppe sammenslåingen ved bruk av `/`, syns teksten blir tungvindt å lese da.

2020-11-30 07:44 UTC, x10an14 commented on docs/basics/teams.md
> +A service account is also a `--member` of a project, but instead of running the command using in the previous paragraph, you change `--member=user:<email>` to `--member=serviceAccount:<email>`.
At lenken til markdown header innad samme fil fungerer translert til http

2020-11-30 07:45 UTC, x10an14 commented on docs/basics/teams.md
> +Remember to clean up after yourself, so we don't have unnecessary resources running, and costing us money.
Tror setningen i forslaget mitt fungerer uten ordet leveraged, når jeg tenker meg om...

2020-11-30 07:47 UTC, x10an14 commented on docs/basics/teams.md
> +Google Docs has a list of possible [predefined roles](https://cloud.google.com/iam/docs/understanding-roles#predefined_roles) that we recommend using.
`keep in mind/use.` burde funke? Hva tenker du? =)

2020-11-30 09:05 UTC, Kyrremann commented on docs/basics/teams.md
> +Google Docs has a list of possible [predefined roles](https://cloud.google.com/iam/docs/understanding-roles#predefined_roles) that we recommend using.
Funker bedre, slipper å lese hele setningen på nytt.

2020-11-30 09:16 UTC, x10an14 commented on docs/basics/teams.md
> +gcloud projects add-iam-policy-binding <PROJECT_ID> --member=user:<FIRSTNAME>.<LASTNAME>@nav.no --role=<ROLE_NAME> --condition="expression=request.time < timestamp('$(date -v '+1H' -u +'%Y-%m-%dT%H:%
Tar du den du? Får ikke enkelt editert mer enn én linje sånn som dette fungerer...
Bryr meg lite om det er utenfor eller inni (kommentaren).

2020-11-30 09:19 UTC, x10an14 approved these changes
LGTM!

2020-11-30 09:58 UTC, merged