Secure log: Hva menes med "team" + refaktorering
nais/doc pull request #250
Opened 2022-06-09 09:09 UTC by ahusby

Løser https://github.com/nais/doc/issues/249

2022-06-09 09:17 UTC, Kyrremann requested changes

2022-06-09 09:17 UTC, Kyrremann commented on docs/observability/logs/README.md
> +Ask in the [#atom](https://nav-it.slack.com/archives/C7TQ25L9J) Slack channel to connect AD-group X to Github-team Y.
```suggestion
Ask in the [#atom](https://nav-it.slack.com/archives/C7TQ25L9J) Slack channel to connect the AD-group X you made in the previous step to your [nais-team](../../basics/teams) Y.
```
Tror det er viktig at vi beholder ordet nais-team, da vi har et skille mellom nais-teams i NAV og "vanlige" AD-teams. Selv om et nais-team er et AD-team i bunn, så opprettes de på forskjellige måter. Du kan se alle nais-teams i [navikt/teams](https://github.com/navikt/teams).

2022-06-09 09:17 UTC, Kyrremann commented on docs/observability/logs/README.md
> +The logs your apps produces are linked with your Github-team. Someone must create a role in Kibana with read rights to those logs. Whoever is in the AD-group will get the Kibana role, and can thus re
```suggestion
The logs your apps produces are linked with your nais-team.
Administrators of Kibana will create a role your your team with read rights to those logs.
Whoever is in the AD-group (created in step 1) will get the Kibana role, and can thus read all logs produced by apps belonging to the nais-team.
```

Tror med fordel dette kunne vært flyttet en linje opp, slik at det blir en introduksjon til dette steget (steg 2). Og at da den forrige linjen da blir hvordan man løser dette.

2022-06-09 09:42 UTC, ahusby commented
@Kyrremann Hva synes du nå? Og er den relative lenken til doc av nais-teams riktig (funka ikke hos meg, men det er kanskje noe spesielt fordi det er en PR?)?

2022-06-09 10:44 UTC, Kyrremann commented on docs/observability/logs/README.md
> +Ask in the [#atom](https://nav-it.slack.com/archives/C7TQ25L9J) Slack channel to connect the AD-group to your nais-team.
```suggestion
Ask in the [#atom](https://nav-it.slack.com/archives/C7TQ25L9J) Slack channel to connect the AD-group (created in step 1) to your nais-team.
```
Bare for å gjøre det mer eksplisitt.

2022-06-10 06:01 UTC, Kyrremann approved these changes

2022-06-10 06:01 UTC, merged