Add page authors and fix all the links
nais/doc pull request #574
Opened 2024-01-04 11:32 UTC by Starefossen

2024-01-04 11:58 UTC, thokra-nav commented
Hvordan ender dette å se ut? Og er det nødvendig?

2024-01-04 12:51 UTC, kimtore requested changes
<img width="465" alt="image" src="https://github.com/nais/doc/assets/791756/f15b0416-8375-436e-a67b-e20d7b3c2977">

Ser ut som det er noe syntax-feil her?
Lurer også på hva denne authors-endringer faktisk medfører, jeg klarte ikke å se noe når jeg kjører opp docs lokalt?
Ellers LGTM 👍

2024-01-04 21:55 UTC, Starefossen commented
Har lagt til caching av poetry pakker og bygge-cache.
Fant feilen i et av diagrammene, takk for heads up @kimtore 🙏🏻 

Ang. hvordan commiters ser ut så ser det slik ut:

<img width="517" alt="Screenshot 2024-01-04 at 22 55 22" src="https://github.com/nais/doc/assets/968267/1b024728-6d80-4d81-8565-7d9f5f7e5c99">

Tanken er at det kan være litt kult for de som submitter fikses til dokumentasjonen å få navn og bilde at de har bidratt, en slags badge of honor.

2024-01-09 09:26 UTC, thokra-nav commented
Ikke sikker på om jeg føler vi har  behovet, men skal ikke sette meg ordentlig på bakbeina heller.

Men er det mulig å opte ut? Personlig ikke så interessert i å ha ansiktet/navnet mitt i doc-en (selv om det er nav-minionen min)

2024-01-10 10:50 UTC, Starefossen commented
Nei, det er ikke mulig å opt-ut enkeltpersoner. Jeg har satt den som disabled for øyeblikket slik at vi kan få denne merget men jeg mener at det hadde vært en nais gest for å gi cred til de som er med å gjøre en jobb på dokumentasjonen vår.

2024-01-11 11:11 UTC, thokra-nav approved these changes

2024-01-11 15:16 UTC, merged